sudo: false
addons:
  apt:
    packages:
    - gcc-multilib
    - g++-multilib
    - lua5.2
    - libxml-libxml-perl
    - libxml-libxslt-perl
    - zlib1g-dev:i386
language: cpp
before_install:
  pip install --user sphinx
script:
- git tag tmp-travis-build
- sh travis/git-info.sh
- python travis/pr-check-base.py
- python travis/lint.py
- python travis/authors-rst.py
- python travis/script-in-readme.py
- python travis/script-syntax.py --ext=lua --cmd="luac5.2 -p"
- python travis/script-syntax.py --ext=rb --cmd="ruby -c" --path scripts/
- mkdir build-travis
- cd build-travis
- cmake .. -DBUILD_DOCS:BOOL=ON
- make -j3
notifications:
  email: false
